# Copyright 2013 the Neutrino authors (see AUTHORS).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

module $core {

  source [
    "block.n",
    "bool.n",
    "call_literal.n",
    "control.n",
    "core.n",
    "escape.n",
    "exported_service.n",
    "float32.n",
    "foreign_service.n",
    "function.n",
    "integer.n",
    "lambda.n",
    "null.n",
    "object.n",
    "promise.n",
    "selector.n",
    "string.n",
    "tuple.n"
  ]

}
